In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
xs = np.array([-7.0, -5.0, -3.0, 1.0, 3.0, 5.0])
ys = np.array([3.0, 5.0, 7.0, 11.0, 13.0, 15.0])

In [ ]:
tf.random.set_seed(42)
x_tf = tf.cast(tf.constant(xs), tf.float32)
y_tf = tf.cast(tf.constant(ys), tf.float32)

In [ ]:
x_tf, y_tf

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([-7., -5., -3.,  1.,  3.,  5.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 3.,  5.,  7., 11., 13., 15.], dtype=float32)>)

In [ ]:
# creating a sample model
model = tf.keras.Sequential([
tf.keras.layers.Dense(1)
])

# compile a model
model.compile(
    loss = tf.keras.losses.mae,
    optimizer= tf.keras.optimizers.SGD(),
    metrics=["mae"]
)

# fitting a model with changing the no.of epochs to get the better output
model.fit(x_tf,y_tf, epochs=10)

In [ ]:
x_tf, y_tf

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([-7., -5., -3.,  1.,  3.,  5.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 3.,  5.,  7., 11., 13., 15.], dtype=float32)>)

In [ ]:
model.predict([7])

array([[3.39042]], dtype=float32)

In [ ]:
# creating s new model 
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1)
])
# create new complier
model2.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
    loss = tf.keras.losses.mae,
    metrics=["mae"]
)

# fitting a model
model2.fit(x_tf, y_tf, epochs=100)


In [ ]:
model2.predict([20])

array([[32.79895]], dtype=float32)

In [ ]:
# creating more sample data for predection 
xs1 = tf.range(-200, 40, 4)
xs1

<tf.Tensor: shape=(60,), dtype=int32, numpy=
array([-200, -196, -192, -188, -184, -180, -176, -172, -168, -164, -160,
       -156, -152, -148, -144, -140, -136, -132, -128, -124, -120, -116,
       -112, -108, -104, -100,  -96,  -92,  -88,  -84,  -80,  -76,  -72,
        -68,  -64,  -60,  -56,  -52,  -48,  -44,  -40,  -36,  -32,  -28,
        -24,  -20,  -16,  -12,   -8,   -4,    0,    4,    8,   12,   16,
         20,   24,   28,   32,   36], dtype=int32)>

In [ ]:
ys1 = xs1 + 10
ys1

In [ ]:
# creating more sample data
xs2 = tf.range(40, 400, 4)
ys2 = xs2 + 10
xs2, ys2

In [ ]:
# recreating the model2 as model3
model3 = tf.keras.Sequential([
        tf.keras.layers.Dense(100, activation='relu'),
        tf.keras.layers.Dense(1)
])

# create new complier
model3.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
    loss = tf.keras.losses.mae,
    metrics=["mae"]
)



In [ ]:
# fitting a model
model3.fit(xs1, ys1, epochs=100)
model3.fit(xs2,ys2, epochs=100)

In [ ]:
model3.predict([125])

array([[135.52118]], dtype=float32)

In [ ]:
# Checking the summary for that paticular model
model = tf.keras.Sequential([
      tf.keras.layers.Dense(10, input_shape=[1], name='input_layer'),
      tf.keras.layers.Dense(1, name='output_layer')
],  name = 'model_1')

# compile the model
model.compile(
    optimizer=tf.optimizers.SGD(),
    loss=tf.losses.mae,
    metrics = ['mae']
)


In [ ]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (Dense)          (None, 10)                20        
_________________________________________________________________
output_layer (Dense)         (None, 1)                 11        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model_valid = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(20,20,3), name='dens_layer_1'),
    tf.keras.layers.Conv2D(32, kernel_size=(3,3), activation='relu', padding='same', name='conv_layer_1'),
    tf.keras.layers.Conv2D(64, kernel_size=(5,5), activation='relu', padding='same'),
    tf.keras.layers.Conv2D(128, kernel_size=(7,7), activation='relu', padding='same'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(2, activation='softmax')
])

In [ ]:
model_valid.summary()

In [ ]:
model_xs2 = tf.keras.models.Sequential([
    tf.keras.layers.Dense(100,activation='relu', input_shape = [1], name='Input_Layer'),
    tf.keras.layers.Dense(1)
    # tf.keras.layers.Dense(4,activation='relu', name='second_dense_layer'),
    # tf.keras.layers.Dense(4,activation='relu', name='third_dense_layer')
])
# compile a model_xs2
model_xs2.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    loss = tf.keras.losses.mae,
    metrics=["mae"]
)


In [ ]:
model_xs2.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (Dense)          (None, 100)               200       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# splitting the data for tranning and testnig on xs2
xs2_train = xs2[:60]
xs2_test = xs2[60:]
xs2_train, xs2_test

(<tf.Tensor: shape=(60,), dtype=int32, numpy=
 array([ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76,  80,  84,  88,
         92,  96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140,
        144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192,
        196, 200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244,
        248, 252, 256, 260, 264, 268, 272, 276], dtype=int32)>,
 <tf.Tensor: shape=(30,), dtype=int32, numpy=
 array([280, 284, 288, 292, 296, 300, 304, 308, 312, 316, 320, 324, 328,
        332, 336, 340, 344, 348, 352, 356, 360, 364, 368, 372, 376, 380,
        384, 388, 392, 396], dtype=int32)>)

In [ ]:
# splitting the data for tranning and testnig on ys2
ys2_train = ys2[:60]
ys2_test = ys2[60:]
ys2_train, ys2_test

(<tf.Tensor: shape=(60,), dtype=int32, numpy=
 array([ 50,  54,  58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98,
        102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150,
        154, 158, 162, 166, 170, 174, 178, 182, 186, 190, 194, 198, 202,
        206, 210, 214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254,
        258, 262, 266, 270, 274, 278, 282, 286], dtype=int32)>,
 <tf.Tensor: shape=(30,), dtype=int32, numpy=
 array([290, 294, 298, 302, 306, 310, 314, 318, 322, 326, 330, 334, 338,
        342, 346, 350, 354, 358, 362, 366, 370, 374, 378, 382, 386, 390,
        394, 398, 402, 406], dtype=int32)>)

In [ ]:
model_xs2.fit(xs2_train, ys2_train, epochs=500)

In [ ]:
ys2_predict = model_xs2.predict(xs2_test)
ys2_predict

In [ ]:
import matplotlib.pyplot as plt

def plot_prediction(x_train, y_train, x_test, y_test, x_pred, y_pred):
  # to visulize the data between train,test and predict
  plt.figure(figsize=(15,10))
  # plot tranning data
  plt.scatter(x_train, y_train, label='Trained Data', c='b') 
  # plot test data
  plt.scatter(x_test, y_test, label='Tested Data', c='g')
  # plot predicted data
  plt.scatter(x_pred, y_pred, label='predicted Data', c='r') 
  # show the data
  plt.legend();


In [ ]:
plot_prediction(
    x_train=xs2_train, 
    y_train=ys2_train,
     x_test=xs2_test, 
     y_test=ys2_test, 
     x_pred=xs2_test, 
     y_pred=ys2_predict
     )

In [ ]:
# ys2_test
ys2_predict

In [ ]:
# finding mean absolute Error
mae = tf.metrics.mean_absolute_error(y_true=ys2_test, y_pred=tf.squeeze(ys2_predict))
mae

<tf.Tensor: shape=(), dtype=float32, numpy=4.6300373>

In [ ]:
# finding mean absolute square error
mse = tf.metrics.mean_squared_error(y_true=ys2_test, y_pred=tf.squeeze(ys2_predict))
mse

<tf.Tensor: shape=(), dtype=float32, numpy=22.374907>